# Generated by ./update.sh - do not update manually!
# Last updated: 2024-09-28
{
  version = "v2.6.16";
  amd64_url = "https://github.com/NapNeko/NapCatQQ/releases/download/v2.6.16/NapCat.Shell.zip";
  amd64_hash = "sha256-UxsDe2zbMZioIinH6wErBrK5SI6QuOGJaIRJI0r5gxU=";
}