{ ... }: {
  # Generated by /update.sh - do not update manually!
  # Last updated: 2025-05-25.
  napcat_version = "v4.7.70";
  napcat_url = "https://github.com/NapNeko/NapCatQQ/releases/download/v4.7.70/NapCat.Shell.zip";
  napcat_hash = "sha256-4j53VhbUKYJuXUjaO1sEgQq9ceY2+JDLItFYHnvkjFo=";
  qq_version = "3.2.17-2025.5.21";
  qq_amd64_url = "https://dldir1.qq.com/qqfile/qq/QQNT/Linux/QQ_3.2.17_250521_amd64_01.deb";
  qq_amd64_hash = "sha256-BG6Qz+hquexSa5QCwWx6vucb4TS0dUQ6UYKB/zkkI1g=";
  qq_arm64_url = "https://dldir1.qq.com/qqfile/qq/QQNT/Linux/QQ_3.2.17_250521_arm64_01.deb";
  qq_arm64_hash = "sha256-PdZ9yHyyx55Y6J59ZsjDsXhXHyNkk1JBS9K0i0vuX/Q=.";
}