{ ... }: {
  # Generated by /update.sh - do not update manually!
  # Last updated: 2026-02-11.
  napcat_version = "v4.15.19";
  napcat_url = "https://github.com/NapNeko/NapCatQQ/releases/download/v4.15.19/NapCat.Shell.zip";
  napcat_hash = "sha256-cAFj/BWe8alpMnIBUrxbRO7Vt2vc7nKC+YNl+16C/dQ=";
  qq_version = "3.2.22-42941";
  qq_amd64_url = "https://dldir1v6.qq.com/qqfile/qq/QQNT/58276046/linuxqq_3.2.22-42941_amd64.deb";
  qq_amd64_hash = "sha256-PwBL2yRrMZTSdsY26pbLQKfguBP+pHCVfRMx6AMyvVQ=";
  qq_arm64_url = "https://dldir1v6.qq.com/qqfile/qq/QQNT/58276046/linuxqq_3.2.22-42941_arm64.deb";
  qq_arm64_hash = "sha256-3HBpnLkO/an/E876Q0A2mG5JNBafxUdm33DL6KLjeZk=";
}